name: App – Build & Deploy Scorecard (dev)

on:
  push:
    branches:
      - main
    paths:
      - "apps/scorecard/**"
      - "infra/container-images/scorecard-app/**"
      - "infra/scripts/build_and_push_images.sh"
      - ".github/workflows/deploy_scorecard.yml"
      - "infra/pipelines/github-actions/deploy_scorecard.yml"
  workflow_dispatch:

env:
  SERVICE_NAME: scorecard-app
  IMAGE_NAME: scorecard-app
  ENVIRONMENT: dev
  REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}          # e.g. myregistry.azurecr.io
  RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}  # e.g. 4th-grc-dev-rg
  CONTAINERAPP_NAME: scorecard-app                     # Azure Container App name

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    name: Build & Deploy Scorecard (dev)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🔐 Login to Azure (OIDC / service principal from AZURE_CREDENTIALS)
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 🐳 Login to container registry
      - name: Docker login to registry
        if: env.REGISTRY != ''
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login $REGISTRY \
            --username "${{ secrets.ACR_USERNAME }}" --password-stdin

      # 🏗 Build & push image using shared infra script
      - name: Build & push scorecard image
        run: |
          chmod +x infra/scripts/build_and_push_images.sh
          ./infra/scripts/build_and_push_images.sh "$IMAGE_NAME" "$REGISTRY" "$GITHUB_SHA"

      # 🚀 Deploy to Azure Container Apps
      # Assumes the Container App is already created by Terraform/IaC.
      - name: Deploy image to Azure Container App
        run: |
          az containerapp update \
            --name "$CONTAINERAPP_NAME" \
            --resource-group "$RESOURCE_GROUP" \
            --image "$REGISTRY/$IMAGE_NAME:$GITHUB_SHA"
